name: Build and push to TdA
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v6.8.0
        with:
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: tda-generic:latest
          outputs: type=docker,dest=/tmp/tda-generic.tar

      - name: Export Environment Variables
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo DB_HOST=$DB_HOST >> ./server/.env
          echo DB_USER=$DB_USER >> ./server/.env
          echo DB_PASSWORD=$DB_PASSWORD >> ./server/.env
          echo DB_NAME=$DB_NAME >> ./server/.env

      - name: Upload to TdA
        uses: Tour-de-App/upload-app@tda-25
        with:
          team_token: ${{ secrets.TEAM_TOKEN }}
          image_name: tda-generic
          image_path: /tmp/tda-generic.tar
